feat: add ReadMe
sdtrachsel/memedepot pull request #27
Opened 2023-06-03 15:29 UTC by emlindvall

## Describe your changes:
**-readme.md:** Updated readme for this project
**- memeImages.js:** Removed running Hopper image to get us back to an even number 

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have tested the functionality of any new or updated features in the browser, if applicable
- [x] I have added a "Reviewer" to review & merge
- [x] If applicable, my code passes all tests

2023-06-03 18:34 UTC, sdtrachsel commented on README.md
> +First things first, **The Meme Depot** is not authorized by, nor in any way officially connected, associated, or affiliated with The Home Depot. Tenuous legality aside, Home Depot is a web-based appl
18 images now :) 
Also, Meme Depot? "Tenuous legality aside, **_Home Depot_** is a web-based application designed to help dads and dad joke-afficianados......"

2023-06-03 18:38 UTC, sdtrachsel requested changes
Looking Good! Nice linguistic skills. 

I made a comment where there are two possible changes in the About section.  I'm not seeing the deployed link. I maybe blind....

2023-06-04 17:06 UTC, sdtrachsel approved these changes

2023-06-04 17:33 UTC, CodeMeister362 approved these changes
Readme is on point!

2023-06-04 17:34 UTC, merged